# Generated by Django 4.0.2 on 2022-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_testmodel_alter_employee_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[(1, 'Software Developer'), (2, 'QA Engineer'), (3, 'DEVOPS Engineer')], default=1, max_length=19),
            preserve_default=False,
        ),
    ]
