# Generated by Django 4.0.2 on 2022-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_delete_testmodel_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='companies',
            field=models.CharField(choices=[('SoftUni', 'SoftUni'), ('Google', 'Google'), ('Facebook', 'Facebook')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software Developer'), (2, 'QA Engineer'), (3, 'DEVOPS Engineer')]),
        ),
    ]
