# Generated by Django 4.0.2 on 2022-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_companies_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.CharField(max_length=10, unique=True, verbose_name='EGN'),
        ),
    ]
