# Generated by Django 4.0.2 on 2022-02-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_user_id_alter_user_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_tittle',
            new_name='job_title',
        ),
    ]
