# Generated by Django 4.0.2 on 2022-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auditentity_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='empployees',
            new_name='employees',
        ),
        migrations.RemoveField(
            model_name='department',
            name='auditentity_ptr',
        ),
        migrations.AddField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AuditEntity',
        ),
    ]
